### ISSUE TITLE
apache error

### ISSUE THREAD

**Issue by leknoppix** [EdBoraas/apache-docker#1]
I can't use this contener. I have this message

docker run --name webServer -ti -p 80:80 -v /var/www/:/var/www/ eboraas/apache
AH00526: Syntax error on line 43 of /etc/apache2/mods-enabled/ssl.conf:
SSLSessionCache: 'shmcb' session cache not supported (known names: ). Maybe you need to load the appropriate socache module (mod_socache_shmcb?).
Action '-D FOREGROUND' failed.
The Apache error log may have more information.

**Comment by EdBoraas** [comment]
I apologize. I've been keeping this up to date on bitbucket, and the images on Docker Hub were fixed a short time ago. I guess I've been bad about keeping github current on this; sorry.
