### ISSUE TITLE
service php7.3-fpm doesn't start automatically

### ISSUE THREAD

**Issue by daniellopesjp** [EdBoraas/apache-docker#4]
After the last update, I have problem with my laravel application, and I found  that the problems is occurs because the php-fpm doesn't start automatically.

> error.log

_[Sat Oct 05 02:03:30.554009 2019] [proxy:error] [pid 17:tid 139733338388224] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.3-fpm.sock (*) failed
[Sat Oct 05 02:03:30.554098 2019] [proxy_fcgi:error] [pid 17:tid 139733338388224] [client 172.17.0.1:46024] AH01079: failed to make connection to backend: httpd-UDS, referer: http://localhost/painel_

To run my application, it's need to into in the container and start the php-fpm with command bellow:

service php7.3-fpm start

**Comment by EdBoraas** [comment]
I've now rolled this change back, so we're back to mod_php/prefork for buster. Should be working again now; thanks for the report!
